/**
 * Schema Categorization Types
 *
 * Types for auto-heuristic tagging and schema categorization.
 * Replaces static negative constraints with positive taxonomy.
 */

// === Category Types ===

/**
 * Built-in category names for schema classification.
 */
export type BuiltInCategory =
  | 'business_core'       // Core CRM objects (Account, Contact, Opportunity)
  | 'business_extended'   // Objects with lookups to core (custom objects linked to Account, etc.)
  | 'system'              // System/Tooling API objects
  | 'system_derived'      // System-generated objects (Feed, History, Share)
  | 'managed_package'     // Objects from managed packages (non-standard namespace)
  | 'custom_metadata'     // Custom Metadata Types (*__mdt)
  | 'platform_event'      // Platform Events (*__e)
  | 'big_object'          // Big Objects (*__b)
  | 'external_object'     // External Objects (*__x)
  | 'lifecycle'           // Status/Stage fields
  | 'user_context'        // User-related fields and objects
  | 'temporal'            // Date/Time fields
  | 'financial'           // Currency/Amount fields
  | 'identity'            // ID and reference fields
  | 'content';            // Content/Document related

/**
 * Custom category type for user-defined categories.
 */
export type CustomCategory = `custom:${string}`;

/**
 * Union of all category types.
 */
export type CategoryName = BuiltInCategory | CustomCategory;

// === Heuristic Rule Types ===

/**
 * Types of heuristic rules for auto-tagging.
 */
export type HeuristicRuleType =
  | 'HAS_LOOKUP_TO'       // Object has lookup relationship to specified target
  | 'NAMESPACE'           // Object/field has specific namespace
  | 'APINAME_PATTERN'     // API name matches pattern (*__mdt, *__e, etc.)
  | 'DERIVED_FROM'        // Object is derived from parent (Feed, History, Share)
  | 'FIELD_PATTERN'       // Field name matches pattern (*Status*, *Stage*)
  | 'FIELD_TYPE'          // Field has specific type
  | 'OBJECT_SUBTYPE'      // Object has specific subtype (from graph)
  | 'OBJECT_CATEGORY';    // Object has specific category (from graph)

/**
 * A heuristic rule for auto-categorization.
 */
export interface HeuristicRule {
  /** Unique identifier for this rule */
  id: string;
  /** Rule type */
  type: HeuristicRuleType;
  /** Target value for the rule (e.g., "Account" for HAS_LOOKUP_TO) */
  target: string;
  /** Category to assign when rule matches */
  assignCategory: CategoryName;
  /** Base confidence for this rule */
  confidence: number;
  /** Priority (higher = evaluated first) */
  priority: number;
  /** Human-readable description */
  description: string;
  /** Whether this rule applies to objects, fields, or both */
  appliesTo: 'object' | 'field' | 'both';
}

// === Category Assignment Types ===

/**
 * Source of a category assignment.
 */
export type CategorySource = 'heuristic' | 'manual' | 'semantic';

/**
 * A category assignment for a schema element.
 */
export interface CategoryAssignment {
  /** The assigned category */
  category: CategoryName;
  /** Confidence of the assignment (0-1) */
  confidence: number;
  /** How the category was assigned */
  source: CategorySource;
  /** The rule that triggered this assignment (for heuristic source) */
  rule?: string;
  /** Timestamp of assignment */
  assignedAt: Date;
}

/**
 * A categorized schema element.
 */
export interface CategorizedElement {
  /** Node type (Object or Field) */
  nodeType: 'Object' | 'Field';
  /** API name of the element */
  apiName: string;
  /** For fields, the parent object API name */
  sobjectType?: string;
  /** All category assignments for this element */
  categories: CategoryAssignment[];
  /** Primary category (highest confidence) */
  primaryCategory?: CategoryAssignment;
}

// === Category Node Types ===

/**
 * Category node data for Neo4j.
 */
export interface CategoryNode {
  /** Category name (unique) */
  name: CategoryName;
  /** Human-readable description */
  description: string;
  /** Whether this was auto-generated by heuristics */
  isAutoGenerated: boolean;
  /** Parent category for hierarchy (optional) */
  parentCategory?: CategoryName;
  /** Example values/entities for this category */
  examples: string[];
  /** The heuristic rule that generated this category (if auto-generated) */
  heuristicRule?: string;
  /** Vector embedding for semantic matching */
  embedding?: number[];
  /** Content hash for change detection */
  contentHash?: string;
}

// === SOQL Pattern Mapping ===

/**
 * SOQL pattern suggestion for a category.
 */
export interface CategorySoqlPattern {
  /** Category name */
  category: CategoryName;
  /** SOQL pattern template */
  pattern: string;
  /** Description of when to use this pattern */
  description: string;
  /** Fields typically involved */
  fields: string[];
  /** Example SOQL */
  example?: string;
}

// === Service Interface ===

/**
 * Options for categorization operations.
 */
export interface CategorizationOptions {
  /** Organization ID */
  orgId?: string;
  /** Whether to use heuristic rules */
  enableHeuristics?: boolean;
  /** Whether to use semantic matching */
  enableSemanticMatching?: boolean;
  /** Minimum confidence for assignments */
  minConfidence?: number;
  /** Custom rules to use in addition to defaults */
  customRules?: HeuristicRule[];
  /** Progress callback */
  onProgress?: (current: number, total: number) => void;
}

/**
 * Result of categorizing a batch of elements.
 */
export interface CategorizationResult {
  /** Number of elements processed */
  processed: number;
  /** Number of elements categorized */
  categorized: number;
  /** Number of categories created */
  categoriesCreated: number;
  /** Categories used */
  categoriesUsed: CategoryName[];
  /** Any errors encountered */
  errors: Array<{ element: string; error: string }>;
}

/**
 * Anti-pattern detection result.
 */
export interface AntiPatternWarning {
  /** Type of anti-pattern detected */
  type: 'category_mismatch' | 'system_object_query' | 'metadata_type_data_query';
  /** The object/field involved */
  element: string;
  /** Detected category */
  detectedCategory: CategoryName;
  /** Expected category based on context */
  expectedCategory?: CategoryName;
  /** Warning message */
  message: string;
  /** Severity level */
  severity: 'info' | 'warning' | 'error';
  /** Suggested alternative */
  suggestion?: string;
}

/**
 * Interface for the schema categorization service.
 */
export interface SchemaCategorization {
  /**
   * Categorize an object based on heuristics.
   */
  categorizeObject(apiName: string, options?: CategorizationOptions): Promise<CategorizedElement>;

  /**
   * Categorize a field based on heuristics.
   */
  categorizeField(
    apiName: string,
    sobjectType: string,
    options?: CategorizationOptions
  ): Promise<CategorizedElement>;

  /**
   * Get the primary category for an object.
   */
  getObjectCategory(apiName: string): Promise<CategoryName | null>;

  /**
   * Get SOQL pattern suggestions for a category.
   */
  getSoqlPatternForCategory(category: CategoryName, value?: string): CategorySoqlPattern[];

  /**
   * Detect anti-patterns in SOQL intent.
   */
  detectAntiPatterns(
    objects: string[],
    userIntent: string
  ): Promise<AntiPatternWarning[]>;

  /**
   * Run heuristic categorization on all objects.
   */
  runHeuristicCategorization(options?: CategorizationOptions): Promise<CategorizationResult>;
}
